version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=overcat
      - TZ=America/Sao_Paulo
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    ports:
      - "5432:5432"
    networks:
      - bridge

  api:
    container_name: overcat-api
    build:
      context: .
      dockerfile: Dockerfile
    image: overcat-api
    environment:
      - postgresql-db.uri=jdbc:postgresql://postgres:5432/overcat
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=senha
    ports:
      - "8080:8080"
    networks:
      - bridge
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  bridge: